# Generated by Django 3.1.1 on 2020-09-16 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lib_mgmt_sys', '0006_authorpenname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='lib_mgmt_sys.author'),
        ),
    ]
