# Generated by Django 3.1.1 on 2020-09-19 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lib_mgmt_sys', '0008_auto_20200917_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorpenname',
            name='author',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='lib_mgmt_sys.author'),
        ),
    ]
