# Generated by Django 3.1.1 on 2020-09-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_mgmt_sys', '0009_auto_20200919_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='cover_photo',
            field=models.ImageField(null=True, upload_to='books_photos'),
        ),
    ]
